### ISSUE TITLE
Restangular swallowing AngularJS exceptions

### ISSUE THREAD

**Issue by riy** [mgonto/restangular#1355]
What happens is when, in my test case, I put this:
```
httpBackend.expectGET('SOME-URL').respond(someResponse);
httpBackend.expectGET('ANOTHER-URL').respond(anotherResponse);
```
... and the order in which they actually get called is this (just reversed):
```
httpBackend.expectGET('ANOTHER-URL').respond(anotherResponse);
httpBackend.expectGET('SOME-URL').respond(someResponse);
```
... then AngularJS used to throw an Exception:
```
Error: Unexpected request: GET SOME-URL
Expected GET ANOTHER-URL
    at $httpBackend (http://localhost:9876/fs/base/src/lib/angular-mocks/angular-mocks.js:1403:9)
    at sendReq (http://localhost:9876/fs/base/src/lib/angular/angular.js:11423:9)
    at serverRequest (http://localhost:9876/fs/base/src/lib/angular/angular.js:11133:16)
    at processQueue (http://localhost:9876/fs/base/src/lib/angular/angular.js:15757:28)
    at http://localhost:9876/fs/base/src/lib/angular/angular.js:15773:27
    at Scope.$eval (http://localhost:9876/fs/base/src/lib/angular/angular.js:17025:28)
    at Scope.$digest (http://localhost:9876/fs/base/src/lib/angular/angular.js:16841:31)
    at Scope.$apply (http://localhost:9876/fs/base/src/lib/angular/angular.js:17133:24)
    at done (http://localhost:9876/fs/base/src/lib/angular/angular.js:11454:47)
    at handleResponse (http://localhost:9876/fs/base/src/lib/angular-mocks/angular-mocks.js:1353:9)
```

What happens with Restangular is that this Exception never makes it to the surface, leaving the developer clueless as to why the test is failing. I only figured this out when I dove deep into the inner workings of Restangular and figured out that I end up in `okCallback` when the response actually contains the above mentioned exception. Yet Restangular attempts to parse the response in the following lines (and fails).
[This](https://github.com/mgonto/restangular/blob/master/src/restangular.js#L1060) is where Restangular goes when it shouldn't, because the call actually failed. It would be helpful if Restangular notices that and propagates the exception up the call stack so it gets printed out.

**Comment by daviesgeek** [comment]
I had a problem with this in my own code (not with Restangular, but a promise). Promises can swallow exceptions, causing odd behavior like what you've experienced. Let me read up on this and get back to you.
