### ISSUE TITLE
"Can't copy! Making copies of Window...." error 

### ISSUE THREAD

**Issue by pareeohnos** [mgonto/restangular#432]
Not entirely sure what's going on here, as I've got a number of other requests running perfectly with almost identical code.

In my Angular controller, I'm setting up a listener for a scope broadcast. In the callback, I am creating a request. Nothing complicated, just as follows:

```
  $scope.$on('notification_name', function(alertID) {
    if (alertID) {
      Restangular.one('resources', resourceID).getList('childresources').then(function(response) {
        $scope.response = response;
      });
    }
  });
```

I am doing almost the exact thing in other controllers, and they are working perfectly, however this one produces the following errors in my console

```
Error: [ng:cpws] Can't copy! Making copies of Window or Scope instances is not supported.
http://errors.angularjs.org/1.2.1/ng/cpws
    at http://localhost:9000/bower_components/angular/angular.js:78:12
    at copy (http://localhost:9000/bower_components/angular/angular.js:803:11)
    at copy (http://localhost:9000/bower_components/angular/angular.js:834:28)
    at copy (http://localhost:9000/bower_components/angular/angular.js:817:23)
    at copy (http://localhost:9000/bower_components/angular/angular.js:834:28)
    at Object.copy (http://localhost:9000/bower_components/angular/angular.js:817:23)
    at Object.config.getFieldFromElem (http://localhost:9000/bower_components/restangular/dist/restangular.js:195:37)
    at Object.config.getUrlFromElem (http://localhost:9000/bower_components/restangular/dist/restangular.js:223:29)
    at http://localhost:9000/bower_components/restangular/dist/restangular.js:572:54
    at Array.reduce (native) 
    (anonymous function) angular.js:9101
    (anonymous function) angular.js:6706
    Scope.$broadcast angular.js:11853
    setAlertId case_factory.js:13
    $scope.highlightFirst controller.js:98
    (anonymous function) controller.js:20
    wrappedCallback angular.js:10597
    (anonymous function) angular.js:10683
    Scope.$eval angular.js:11576
    Scope.$digest angular.js:11421
    $delegate.__proto__.$digest VM3510:844
    Scope.$apply angular.js:11682
    $delegate.__proto__.$apply VM3510:855
    done angular.js:7699
    completeRequest angular.js:7865
    xhr.onreadystatechange
```

There are a number of other requests running at the same time if this causes any issues?

**Comment by crisu83** [comment]
Thanks for the tip about the `$scope.$on`. That solved my problem.
