### ISSUE TITLE
Error: Response for getList SHOULD be an array and not an object or something else

### ISSUE THREAD

**Issue by nagappan** [mgonto/restangular#600]
This code path was working earlier, recently noticed the following exception.

Not sure how to fix it from my end.

Object {data: Array[7], status: 200, headers: function, config: Object, originalElement: Object}
 rest-services.js:19
Error: Response for getList SHOULD be an array and not an object or something else
    at https://cdn.jsdelivr.net/restangular/latest/restangular.js:1059:31
    at B (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:94:5)
    at B (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:94:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:95:173
    at h.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:103:456)
    at h.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:101:218)
    at h.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:104:264)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:68:23)
    at I (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:72:109)
    at XMLHttpRequest.y.onreadystatechange (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js:73:154) 

Additional info:

```
.config(function(RestangularProvider) {
    RestangularProvider.setBaseUrl('rest/index.php');
    RestangularProvider.setDefaultHttpFields({cache: true});
    RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response, deferred) {
        var newResponse = response;
        if (angular.isArray(response)) {
            angular.forEach(newResponse, function(value, key) {
                newResponse[key].originalElement = angular.copy(value);
            });
        } else {
            newResponse.originalElement = angular.copy(response);
        }
        console.log(newResponse);
        return newResponse;
    });
})
```

Thanks

**Comment by rck935** [comment]
Question question:
do getList() encodes the array? 
i.e. **Restangular.one(url).getList('sampleRefId', array);
**because I am observing that in my code. So, we don't have to use **encodeURIComponent**
