### ISSUE TITLE
Notify Progress Examples in Restangular

### ISSUE THREAD

**Issue by subramn** [mgonto/restangular#672]
Hi,

Are there are any good examples which i can refer for implementing Progress notification using Restangular.

**Comment by manojguptagit** [comment]
It breaks when used with RestAngular POST

--------------------------------------------------------------------------------
 SyntaxError: Unexpected token D
    at Object.parse (native)
    at uc (http://localhost:8080/assets/vendor/angular/angular.min.js:15:483)
    at $b (http://localhost:8080/assets/vendor/angular/angular.min.js:82:360)
    at http://localhost:8080/assets/vendor/angular/angular.min.js:83:274
    at n (http://localhost:8080/assets/vendor/angular/angular.min.js:7:333)
    at cd (http://localhost:8080/assets/vendor/angular/angular.min.js:83:256)
    at c (http://localhost:8080/assets/vendor/angular/angular.min.js:84:468)
    at http://localhost:8080/assets/vendor/angular/angular.min.js:119:129
    at r.$eval (http://localhost:8080/assets/vendor/angular/angular.min.js:133:313)
    at r.$digest (http://localhost:8080/assets/vendor/angular/angular.min.js:130:412)
angular.js:12520 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
-------------------------------------------------------------------------------------------------------------------
