### ISSUE TITLE
Restangular.several() throws TypeError

### ISSUE THREAD

**Issue by ScreenDriver** [mgonto/restangular#939]
I can't use Restangular.several(). I am calling

```javascript
Restangular
  .several('path', 1, 2, 3)
  .get()
  .then(...)
```

I am not calling .getList() because /path/1 does not return a list but a single object. Unfortunately I get following error

```javascript
[console.error] TypeError: Cannot call method 'toString' of undefined
    at Array.getById (http://192.168.0.36:3000/bower_components/restangular/dist/restangular.js:1011:44)
    at Array.bound [as get] (http://192.168.0.36:3000/bower_components/lodash/dist/lodash.compat.js:1005:21)
    at Object.returnObject.refresh (http://192.168.0.36:3000/scripts/services/foo.js:108:55)
    at http://192.168.0.36:3000/scripts/controllers/bar.js:68:34
    at wrappedCallback (http://192.168.0.36:3000/bower_components/angular/angular.js:11573:81)
    at http://192.168.0.36:3000/bower_components/angular/angular.js:11659:26
    at Scope.$eval (http://192.168.0.36:3000/bower_components/angular/angular.js:12702:28)
    at Scope.$digest (http://192.168.0.36:3000/bower_components/angular/angular.js:12514:31)
    at Scope.$apply (http://192.168.0.36:3000/bower_components/angular/angular.js:12806:24)
    at done (http://192.168.0.36:3000/bower_components/angular/angular.js:8379:45)
```

If I use .getList() I get a "Response for getList SHOULD be an array and not an object or something else" (that's true therefore I want to use .get())

**Comment by grabbou** [comment]
Ok, sounds like an urgent bug to be fixed. Writing that down for nearest release.

**Comment by grabbou** [comment]
If your response is a single object than what's the point of using several? If you have an array embedded inside object you get from your sever, use response interceptor to parse it as mentioned in the docs and that should work :)
